package com.mohse78.bankcardbase;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table AccountTransactions.
 */
public class AccountTransaction {

    private Long id;
    private Long account_id;
    private Double lastBalance;
    private Double debit;
    private Double credit;
    private Double currentBalance;
    private String description;
    private java.util.Date creationDate;
    private Long transactionType;

    public AccountTransaction() {
    }

    public AccountTransaction(Long id) {
        this.id = id;
    }

    public AccountTransaction(Long id, Long account_id, Double lastBalance, Double debit, Double credit, Double currentBalance, String description, java.util.Date creationDate, Long transactionType) {
        this.id = id;
        this.account_id = account_id;
        this.lastBalance = lastBalance;
        this.debit = debit;
        this.credit = credit;
        this.currentBalance = currentBalance;
        this.description = description;
        this.creationDate = creationDate;
        this.transactionType = transactionType;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getAccount_id() {
        return account_id;
    }

    public void setAccount_id(Long account_id) {
        this.account_id = account_id;
    }

    public Double getLastBalance() {
        return lastBalance;
    }

    public void setLastBalance(Double lastBalance) {
        this.lastBalance = lastBalance;
    }

    public Double getDebit() {
        return debit;
    }

    public void setDebit(Double debit) {
        this.debit = debit;
    }

    public Double getCredit() {
        return credit;
    }

    public void setCredit(Double credit) {
        this.credit = credit;
    }

    public Double getCurrentBalance() {
        return currentBalance;
    }

    public void setCurrentBalance(Double currentBalance) {
        this.currentBalance = currentBalance;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public java.util.Date getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(java.util.Date creationDate) {
        this.creationDate = creationDate;
    }

    public Long getTransactionType() {
        return transactionType;
    }

    public void setTransactionType(Long transactionType) {
        this.transactionType = transactionType;
    }

}
