package com.mohse78.bankcardbase;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table Accounts.
 */
public class Account implements Serializable{

    private Long id;
    private String accountIdOriginal;
    private Boolean forTransaction;
    private Boolean givSms;
    private Double balance;

    public Account() {
    }

    public Account(Long id) {
        this.id = id;
    }

    public Account(Long id, String accountIdOriginal, Boolean forTransaction, Boolean givSms, Double balance) {
        this.id = id;
        this.accountIdOriginal = accountIdOriginal;
        this.forTransaction = forTransaction;
        this.givSms = givSms;
        this.balance = balance;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAccountIdOriginal() {
        return accountIdOriginal;
    }

    public void setAccountIdOriginal(String accountIdOriginal) {
        this.accountIdOriginal = accountIdOriginal;
    }

    public Boolean getForTransaction() {
        return forTransaction;
    }

    public void setForTransaction(Boolean forTransaction) {
        this.forTransaction = forTransaction;
    }

    public Boolean getGivSms() {
        return givSms;
    }

    public void setGivSms(Boolean givSms) {
        this.givSms = givSms;
    }

    public Double getBalance() {
        return balance;
    }

    public void setBalance(Double balance) {
        this.balance = balance;
    }

}
