package com.mohse78.bankcardbase;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table Banks.
 */
public class Bank {

    private Long id;
    private String name;
    private Integer imageLogoId;
    private Integer imageCardId;
    private String cardNumberDefault;
    private Boolean deleted;

    public Bank() {
    }

    public Bank(Long id) {
        this.id = id;
    }

    public Bank(Long id, String name, Integer imageLogoId, Integer imageCardId, String cardNumberDefault, Boolean deleted) {
        this.id = id;
        this.name = name;
        this.imageLogoId = imageLogoId;
        this.imageCardId = imageCardId;
        this.cardNumberDefault = cardNumberDefault;
        this.deleted = deleted;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getImageLogoId() {
        return imageLogoId;
    }

    public void setImageLogoId(Integer imageLogoId) {
        this.imageLogoId = imageLogoId;
    }

    public Integer getImageCardId() {
        return imageCardId;
    }

    public void setImageCardId(Integer imageCardId) {
        this.imageCardId = imageCardId;
    }

    public String getCardNumberDefault() {
        return cardNumberDefault;
    }

    public void setCardNumberDefault(String cardNumberDefault) {
        this.cardNumberDefault = cardNumberDefault;
    }

    public Boolean getDeleted() {
        return deleted;
    }

    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

}
