package com.mohse78.bankcardbase;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table Cards.
 */
public class Card {

    private Long id;
    private Long bank_id;
    private Long account_id;
    private Long person_id;
    private String cardNumber;
    private String cvv2;
    private String expDate;
    private String bankBranchCode;

    public Card() {
    }

    public Card(Long id) {
        this.id = id;
    }

    public Card(Long id, Long bank_id, Long account_id, Long person_id, String cardNumber, String cvv2, String expDate, String bankBranchCode) {
        this.id = id;
        this.bank_id = bank_id;
        this.account_id = account_id;
        this.person_id = person_id;
        this.cardNumber = cardNumber;
        this.cvv2 = cvv2;
        this.expDate = expDate;
        this.bankBranchCode = bankBranchCode;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getBank_id() {
        return bank_id;
    }

    public void setBank_id(Long bank_id) {
        this.bank_id = bank_id;
    }

    public Long getAccount_id() {
        return account_id;
    }

    public void setAccount_id(Long account_id) {
        this.account_id = account_id;
    }

    public Long getPerson_id() {
        return person_id;
    }

    public void setPerson_id(Long person_id) {
        this.person_id = person_id;
    }

    public String getCardNumber() {
        return cardNumber;
    }

    public void setCardNumber(String cardNumber) {
        this.cardNumber = cardNumber;
    }

    public String getCvv2() {
        return cvv2;
    }

    public void setCvv2(String cvv2) {
        this.cvv2 = cvv2;
    }

    public String getExpDate() {
        return expDate;
    }

    public void setExpDate(String expDate) {
        this.expDate = expDate;
    }

    public String getBankBranchCode() {
        return bankBranchCode;
    }

    public void setBankBranchCode(String bankBranchCode) {
        this.bankBranchCode = bankBranchCode;
    }

}
