package com.mohse78.bankcardbase;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SMS_BANK_META_DATA.
 */
public class SmsBankMetaData {

    private Long id;
    private String bankName;
    private String accountNumber;
    private String debitFieldName;
    private String creditFieldName;
    private String description;
    private Double amount;
    private Double balance;
    private java.util.Date date;

    public SmsBankMetaData() {
    }

    public SmsBankMetaData(Long id) {
        this.id = id;
    }

    public SmsBankMetaData(Long id, String bankName, String accountNumber, String debitFieldName, String creditFieldName, String description, Double amount, Double balance, java.util.Date date) {
        this.id = id;
        this.bankName = bankName;
        this.accountNumber = accountNumber;
        this.debitFieldName = debitFieldName;
        this.creditFieldName = creditFieldName;
        this.description = description;
        this.amount = amount;
        this.balance = balance;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getBankName() {
        return bankName;
    }

    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    public String getAccountNumber() {
        return accountNumber;
    }

    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }

    public String getDebitFieldName() {
        return debitFieldName;
    }

    public void setDebitFieldName(String debitFieldName) {
        this.debitFieldName = debitFieldName;
    }

    public String getCreditFieldName() {
        return creditFieldName;
    }

    public void setCreditFieldName(String creditFieldName) {
        this.creditFieldName = creditFieldName;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Double getAmount() {
        return amount;
    }

    public void setAmount(Double amount) {
        this.amount = amount;
    }

    public Double getBalance() {
        return balance;
    }

    public void setBalance(Double balance) {
        this.balance = balance;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

}
